name: First workflow
on: 
    push:
run-name: running first github flow
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: Print greeting
              run: echo "First Step"
            - name: Print second greeting
              run: |
                echo "Hola comment estos"
                echo "Bonjour, ca va?"
    second-job:
        runs-on: ubuntu-latest
        needs: [first-job]
        steps:
            - name: Create a file
              run: echo "haha" > file.txt
            - name: Show files
              run: ls -lrt